### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by k11m1** [DSroD/NewtonianGravitySimulation#1]
Jak se jmenuješ na tom discordu? :D

**Comment by DSroD** [comment]
Zdravím, úplně jsem na tebe zapomněl, na discord v poslední době stejně vůbec nechodím, pošlu ti na mail teamspeak kde se občas na večer ukážu :D

**Comment by k11m1** [comment]
Já teď úplně vzpominal, odkod tě znám :D. Tak já stáhnu teamspeak c:

Dne 11. 12. 2017 2:18 PM napsal uživatel "Daniel Rod" <
notifications@github.com>:
